# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '首次'), (1, '1天'), (2, '3天'), (3, '7天'), (4, '1月'), (5, '3月'), (6, '半年'), (100, '复习')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
