# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20171127_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '首次'), (1, '1天'), (2, '3天'), (3, '7天'), (4, '1月'), (5, '3月'), (6, '半年'), (100, '复习')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='record',
            name='test_times',
            field=models.IntegerField(default=0, verbose_name='次数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='num',
            field=models.SmallIntegerField(verbose_name='个数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '首次'), (1, '1天'), (2, '3天'), (3, '7天'), (4, '1月'), (5, '3月'), (6, '半年'), (100, '复习')], default=0, verbose_name='类型'),
        ),
    ]
