# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20171127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '首次'), (1, '1天'), (2, '3天'), (3, '7天'), (4, '1月'), (5, '3月'), (6, '半年'), (100, '完成')], default=0, verbose_name='状态'),
        ),
    ]
