# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_auto_20171130_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '复习'), (2, '未及时')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '首次'), (1, '1天'), (2, '3天'), (3, '7天'), (4, '15天'), (5, '1月'), (6, '3月'), (7, '半年'), (100, '完成')], default=0, verbose_name='类型'),
        ),
    ]
