# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171111_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未报名'), (1, '已报名')], default=0),
        ),
    ]
